#!/bin/bash
# PDF 解析工具 - 使用方法

echo "📄 PDF 月結單解析工具"
echo "======================"
echo ""
echo "由於 iCloud 檔案鎖定問題，請使用以下方法之一："
echo ""
echo "方法 1: 先複製到本地（推薦）"
echo "------------------------------"
echo "1. 在 Finder 中，選擇 PDF 檔案"
echo "2. 右鍵 → 複製"
echo "3. 貼到 ~/.finance/statements/2026-01/"
echo "4. 然後運行:"
echo ""
echo "   python3 ~/.finance/scripts/pdf_parser.py \\"
echo "     ~/.finance/statements/2026-01/hsbc.pdf hsbc"
echo ""
echo "方法 2: 使用快捷指令自動化"
echo "--------------------------"
echo "創建 macOS 快捷指令："
echo "1. 收到 PDF 時"
echo "2. 移動到 ~/.finance/statements/YYYY-MM/"
echo "3. 執行解析腳本"
echo ""
echo "方法 3: 手動觸發 iCloud 下載"
echo "-----------------------------"
echo "在 Finder 中雙擊 PDF，確保已下載到本地"
echo "然後運行:"
echo ""
echo "   python3 ~/.finance/scripts/pdf_parser.py \\"
echo "     ~/Library/Mobile\\ Documents/com~apple~CloudDocs/Documents/Finance/xxx.pdf"
echo ""
